services:
  back:
    name: back-kotlin
    build: 
      context: ./back-kotlin
      target:  runtime
    image: nbulteau/mystravastats-back-kotlin:latest
    container_name: mystravastats-backend-kotlin
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ${STRAVA_CACHE_PATH}:/app/strava-cache

  front:
    build: ./front-vue
    image: nbulteau/mystravastats-front:latest
    container_name: mystravastats-front
    ports:
      - "80:80"
    depends_on:
      - back
    networks: 
      - front-back     
  
networks: 
  front-back:
    driver: bridge

