services:
  back:
    build: 
      context: ./back-go
      target:  runtime
    image: nbulteau/mystravastats-back-go:latest
    container_name: mystravastats-backend-go
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ${STRAVA_CACHE_PATH}:/app/strava-cache

  front:
    build: ./front-vue
    image: nbulteau/mystravastats-front-vue:latest
    container_name: mystravastats-front-vue
    ports:
      - "80:80"
    depends_on:
      - back
    networks: 
      - front-back     
  
networks: 
  front-back:
    driver: bridge

