package me.nicolas.stravastats.api.dto

import io.swagger.v3.oas.annotations.media.Schema
import me.nicolas.stravastats.domain.business.DashboardData

@Schema(description = "Dashboard data", name = "DashboardData")
data class DashboardDataDto(
    val nbActivitiesByYear: Map<String, Int>,
    val activeDaysByYear: Map<String, Int>,
    val consistencyByYear: Map<String, Float>,
    val movingTimeByYear: Map<String, Int>,
    val totalDistanceByYear: Map<String, Float>,
    val averageDistanceByYear: Map<String, Float>,
    val maxDistanceByYear: Map<String, Float>,
    val maxDistanceDateByYear: Map<String, String>,
    val averageDistanceByActiveDayByYear: Map<String, Float>,
    val maxDistanceByActiveDayByYear: Map<String, Float>,
    val maxDistanceByActiveDayDateByYear: Map<String, String>,
    val totalElevationByYear: Map<String, Int>,
    val averageElevationByYear: Map<String, Int>,
    val maxElevationByYear: Map<String, Int>,
    val maxElevationDateByYear: Map<String, String>,
    val averageElevationByActiveDayByYear: Map<String, Int>,
    val maxElevationByActiveDayByYear: Map<String, Int>,
    val maxElevationByActiveDayDateByYear: Map<String, String>,
    val elevationEfficiencyByYear: Map<String, Float>,
    val averageSpeedByYear: Map<String, Float>,
    val maxSpeedByYear: Map<String, Float>,
    val maxSpeedDateByYear: Map<String, String>,
    val averageHeartRateByYear: Map<String, Int>,
    val maxHeartRateByYear: Map<String, Int>,
    val maxHeartRateDateByYear: Map<String, String>,
    val averageWattsByYear: Map<String, Int>,
    val maxWattsByYear: Map<String, Int>,
    val maxWattsDateByYear: Map<String, String>,
    val deviceAverageWattsByYear: Map<String, Int>,
    val deviceMaxWattsByYear: Map<String, Int>,
    val deviceMaxWattsDateByYear: Map<String, String>,
)

fun DashboardData.toDto(): DashboardDataDto {
    return DashboardDataDto(
        nbActivitiesByYear = this.nbActivitiesByYear,
        activeDaysByYear = this.activeDaysByYear,
        consistencyByYear = this.consistencyByYear,
        movingTimeByYear = this.movingTimeByYear,
        totalDistanceByYear = this.totalDistanceByYear,
        averageDistanceByYear = this.averageDistanceByYear,
        maxDistanceByYear = this.maxDistanceByYear,
        maxDistanceDateByYear = this.maxDistanceDateByYear,
        averageDistanceByActiveDayByYear = this.averageDistanceByActiveDayByYear,
        maxDistanceByActiveDayByYear = this.maxDistanceByActiveDayByYear,
        maxDistanceByActiveDayDateByYear = this.maxDistanceByActiveDayDateByYear,
        totalElevationByYear = this.totalElevationByYear,
        averageElevationByYear = this.averageElevationByYear,
        maxElevationByYear = this.maxElevationByYear,
        maxElevationDateByYear = this.maxElevationDateByYear,
        averageElevationByActiveDayByYear = this.averageElevationByActiveDayByYear,
        maxElevationByActiveDayByYear = this.maxElevationByActiveDayByYear,
        maxElevationByActiveDayDateByYear = this.maxElevationByActiveDayDateByYear,
        elevationEfficiencyByYear = this.elevationEfficiencyByYear,
        averageSpeedByYear = this.averageSpeedByYear,
        maxSpeedByYear = this.maxSpeedByYear,
        maxSpeedDateByYear = this.maxSpeedDateByYear,
        averageHeartRateByYear = this.averageHeartRateByYear,
        maxHeartRateByYear = this.maxHeartRateByYear,
        maxHeartRateDateByYear = this.maxHeartRateDateByYear,
        averageWattsByYear = this.averageWattsByYear,
        maxWattsByYear = this.maxWattsByYear,
        maxWattsDateByYear = this.maxWattsDateByYear,
        deviceAverageWattsByYear = this.deviceAverageWattsByYear,
        deviceMaxWattsByYear = this.deviceMaxWattsByYear,
        deviceMaxWattsDateByYear = this.deviceMaxWattsDateByYear,
    )
}
