package me.nicolas.stravastats.api.dto

import me.nicolas.stravastats.domain.business.strava.SegmentEffort

data class SegmentEffortDto(
    val achievements: List<AchievementDto>,
    val activity: Long,
    val athlete: Long,
    val averageCadence: Double,
    val averageHeartRate: Double,
    val averageWatts: Double,
    val deviceWatts: Boolean,
    val distance: Double,
    val elapsedTime: Int,
    val endIndex: Int,
    val hidden: Boolean,
    val id: Long,
    val komRank: Int?,
    val maxHeartRate: Double,
    val movingTime: Int,
    val name: String,
    val prRank: Int?,
    val resourceState: Int,
    val segment: SegmentDto,
    val startDate: String,
    val startDateLocal: String,
    val startIndex: Int,
    val visibility: String?,
)

fun SegmentEffort.toDto() = SegmentEffortDto(
    achievements = achievements.map { it.toDto() },
    activity = activity.id,
    athlete = athlete.id,
    averageCadence = averageCadence,
    averageHeartRate = averageHeartRate,
    averageWatts = averageWatts,
    deviceWatts = deviceWatts,
    distance = distance,
    elapsedTime = elapsedTime,
    endIndex = endIndex,
    hidden = hidden,
    id = id,
    komRank = komRank,
    maxHeartRate = maxHeartRate,
    movingTime = movingTime,
    name = name,
    prRank = prRank,
    resourceState = resourceState,
    segment = segment.toDto(),
    startDate = startDate,
    startDateLocal = startDateLocal,
    startIndex = startIndex,
    visibility = visibility,
)