package me.nicolas.stravastats.domain.business

data class DashboardData(
    val nbActivitiesByYear: Map<String, Int>,
    val activeDaysByYear: Map<String, Int>,
    val consistencyByYear: Map<String, Float>,
    val movingTimeByYear: Map<String, Int>,
    val totalDistanceByYear: Map<String, Float>,
    val averageDistanceByYear: Map<String, Float>,
    val maxDistanceByYear: Map<String, Float>,
    val maxDistanceDateByYear: Map<String, String>,
    val averageDistanceByActiveDayByYear: Map<String, Float>,
    val maxDistanceByActiveDayByYear: Map<String, Float>,
    val maxDistanceByActiveDayDateByYear: Map<String, String>,
    val totalElevationByYear: Map<String, Int>,
    val averageElevationByYear: Map<String, Int>,
    val maxElevationByYear: Map<String, Int>,
    val maxElevationDateByYear: Map<String, String>,
    val averageElevationByActiveDayByYear: Map<String, Int>,
    val maxElevationByActiveDayByYear: Map<String, Int>,
    val maxElevationByActiveDayDateByYear: Map<String, String>,
    val elevationEfficiencyByYear: Map<String, Float>,
    val averageSpeedByYear: Map<String, Float>,
    val maxSpeedByYear: Map<String, Float>,
    val maxSpeedDateByYear: Map<String, String>,
    val averageHeartRateByYear: Map<String, Int>,
    val maxHeartRateByYear: Map<String, Int>,
    val maxHeartRateDateByYear: Map<String, String>,
    val averageWattsByYear: Map<String, Int>,
    val maxWattsByYear: Map<String, Int>,
    val maxWattsDateByYear: Map<String, String>,
    val deviceAverageWattsByYear: Map<String, Int>,
    val deviceMaxWattsByYear: Map<String, Int>,
    val deviceMaxWattsDateByYear: Map<String, String>,
)
